name=heatshrink
version=0.4.1
author=Scott Vokes
maintainer=Scott Vokes
sentence=An embedded data compression library.
paragraph=Vendored heatshrink encoder used for Marlin Binary File Transfer.
category=Data Processing
url=https://github.com/atomicobject/heatshrink
architectures=*

